POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Yoga Effects on Brain Health: A Systematic Review of the Current Literature",
    "author": "Neha P. Gothea, Imadh Khan",
    "url": "https://content.iospress.com/articles/brain-plasticity/bpl190084"
}