POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvdWdsYXNfYWRhbXMiLCJpZCI6IjVlODllZjlkYWY3YjRlNTk1YTIxZTVlZSIsImlhdCI6MTU4NjQ2NjU3MH0.ZNzI967XgvuLKqOnTRozub6JbOxmEScpgyEFxYQmN50

{
    "title": "The Hitchhiker's Guide to the Galaxy",
    "author": "Douglas Adams",
    "url": "https://www.amazon.com/Hitchhikers-Guide-Galaxy-Douglas-Adams/dp/0345391802",
    "likes": 42
}